### ISSUE TITLE
ui-grid only supports angular up to 1.4 ?

### ISSUE THREAD

**Issue by AmirGilboa** [angular-fullstack/generator-angular-fullstack#2348]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.1
Operating System | Windows 10
etc | etc

Item | Answer
----- | -----
Transpiler | Babel 
Markup | HTML
etc | etc

I worked in 3.7.x with **ui-grid** and it worked well.
now in 4.1.0, it gives me errors like this:
```angular.js:68Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module {} due to:
Error: [ng:areq] Argument 'module' is not a function, got Object
http://errors.angularjs.org/1.5.8/ng/areq?p0=module&p1=not%20a%20function%2C%20got%20Object
    at http://localhost:3000/vendor.bundle.js:194:13
    at assertArg (http://localhost:3000/vendor.bundle.js:2018:12)
```
I read in their doc that the grid supports angular 1.2 - 1.4 only . means, our 1.58 is out.
So? i have to find other grid solution?  any recommendations?  or a solution to this error?

Or maybe this is a webpack issue?

what led to this problem:
1. npm install angular-ui-grid --save
2. app.js:
import uiGrid from 'angular-ui-grid';
...
angular.module('app', [ngCookies, ngResource, ..... uiGrid ... ])

**Comment by Awk34** [comment]
It appears that ui-grid is not maintained. I would suggest looking for an alternative.

**Comment by AmirGilboa** [comment]
maybe others could recommend an alternative...

**Comment by Awk34** [comment]
If you're working on a professional project, you might look into [Kendo UI](http://www.telerik.com/kendo-ui/angularjs-and-kendo-ui-framework-integration)

**Comment by Awk34** [comment]
If you have a hybrid Angular 1/2 app, you can also look into the great options for Angular 2 data grids

**Comment by AmirGilboa** [comment]
yes, looking at kendo now. it's a $1000, but looks like my only choice now. thanks.

**Comment by Awk34** [comment]
More and more Angular 1.x modules will slowly become deprecated. I highly suggest converting your app to a hybrid app. You can scaffold one if you pull down the `ng2-hybrid` branch of this generator. If you're stuck with Angular 1.x for some reason, Kendo is the only one I know of guaranteed to get support, since it's a paid product.
